---
# Specify local paths of BNCDE and TE-CDE model. Specify prediction window


pfn_path: '/content/drive/MyDrive/â˜…BNCDE/runs/lightning_logs/version_9/checkpoints/epoch=0-step=157.ckpt'

informative_sampling: False

window: 'one_step'

# window is specified via 'one_step', 'two_step', 'three_step', 'four_step', 'five_step'

...